pairs = [
['(apakah|saya|perlu|buat|surat|terang|panjang|ktp|jika|ingin|masa|laku)', ['kalau KTP sudah elektrik, maka otomatis akan aktif seumur hidup. Meskipun tertera tanggal berlaku KTP tersebut maka dabaikan saja (karena KTP cetakan pertama masih ada tanggal berlakunya)']] ,
['(bagaimana|cara|buat|surat|terang|panjang|ktp|di|kantor|desa)', ['tidak ada surat perpanjangan KTP']] ,
['(apakah|saya|perlu|buat|surat|terang|ktp|jika|ingin|untuk|pertama|kali)', ['tidak ada surat keterangan, untuk membuat KTP hanya diperlukan Fotocopi Kartu Keluarga dan langsung ke Kantor Catatan Sipil Setempat.']] ,
['(bagaimana|cara|buat|surat|terang|ktp|di|kantor|desa)', ['tidak ada surat keterangan pembuatan KTP']] ,
['(apakah|saya|perlu|buat|surat|terang|pindah|jika|ingin|ubah|alamat|ktp)', ['Tentu Saja. Apabila KTP Anda beralamat di Luar Desa Melati II dan sudah menetap bertempat tinggal di Desa Melati II, maka diharuskan membuat surat Pindah dari Daerah Asal, agar administrasi Anda sesuai dengan tempat tinggal anda yang sekarang']] ,
['(bagaimana|cara|buat|surat|terang|pindah|di|kantor|desa)', ['dengan membawa Kartu Keluarga Asli ke Kantor Desa Setempat dan data alamat tujuan pindah.']] ,
['(apakah|saya|perlu|buat|surat|terang|datang|jika|ingin|ubah|status|ktp)', ['KTP sudah seumur hidup, maka tidak bisa diganti apabila tidak ada elemen yang harus digantikan.']] ,
['(bagaimana|cara|buat|surat|terang|datang|di|kantor|desa)', ['Membawa Kartu Keluarga yang berksangkutan dan Kartu Keluarga rumah yang dikunjungi. Surat Keterangan Datang sama dengan Surat Keterangan Berkunjung.']] ,
['(apakah|saya|perlu|buat|surat|terang|lahir|jika|ingin|ktp|untuk|anak)', ['WNI yang diwajibkan memiliki KTP-El adalah yang sudah berumur 17 Tahun. Maka Apabila Anak Anda sudah berumur 17 Tahun maka sudah bisa melakukan perekaman KTP di Kantor Catatan Sipil Setempat.']] ,
['(bagaimana|cara|buat|surat|terang|lahir|di|kantor|desa)', ['Surat Keterangan Lahir tidak dikeluarkan dari Kantor Desa melainkan dari Kantor Catatan Sipil yakni Akta Kelahiran. Syarat pembuatan Akta Kelahiran, yaitu dengan membawa : Fotocopi Kartu Keluarga, Fotocopi Buku Nikah Orang Tua, Fotocopi KTP Orang Tua, Fotocopi KTP 2 orang saksi (yang masih dalam 1 kabupaten), Surat Keterangan Lahir dari Bidan/Rumah Sakit Asli ke Kantor Desa Setempat dan akan dilengkapi dengan Formulir pembuatan Akta Kelahiran.']] ,
['(apakah|saya|perlu|buat|surat|terang|mati|jika|ingin|ubah|status|ktp)', ['Jika orang yang memiliki KTP sudah meninggal, maka KTP tersebut akan ditarik kembali oleh Kator Catatan Sipil Setempat dan akan digantikan dengan menimbulkan Akta Kematian orang tersebut.']] ,
['(bagaimana|cara|buat|surat|terang|mati|di|kantor|desa)', ['dengan membawa Kartu Keluarga Asli ke Kantor Desa Setempat serta memberitahukan waktu meninggalnya (seperti Umur, Hari, Tanggal meninggalnya)']] ,
['(apakah|saya|perlu|buat|ubah|data|kk|jika|ingin|ktp)', ['Ya. Apabila jika data di KK dan KTP terdapat elemen yang salah, maka harus melakukan Perubahan dahulu.']] ,
['(bagaimana|cara|buat|ubah|data|kk|di|kantor|desa)', ['Dengan membawa Kartu Keluarga Asli dan elemen Pendukung Perubahan tersebut (seperti Ijazah atau Akta Kelahiran) serta membawa Materai 10.000.']] ,
['(apakah|saya|perlu|buat|surat|domisili|tempat|tinggal|jika|ingin|ubah|alamat|ktp)', ['Tidak. Apabila KK sudah beralamat/berdomisili ditempat tersebut, maka hanya perlu membawa fotocopi KK dan KTP asli ke Kantor Catatan Sipil untuk perubahan KTP.']] ,
['(bagaimana|cara|buat|surat|domisili|tempat|tinggal|di|kantor|desa)', ['Apabila orang tersebut beralamat di Luar Desa Melati II, maka harus membuat Surat Mandah dari Desa Asal kemudian di bawa ke Kantor Desa Melati II serta membawa fotocopi KK.']] ,
['(apakah|saya|perlu|buat|surat|terang|riwayat|tanah|jika|ingin|ubah|status|ktp)', ['Tidak.']] ,
['(bagaimana|cara|buat|surat|terang|riwayat|tanah|di|kantor|desa)', ['tidak pernah membuat surat keterangan riwayat tanah.']] ,
['(apakah|saya|perlu|buat|surat|salin|c|jika|ingin|ubah|status|ktp)', ['tidak']] ,
['(bagaimana|cara|buat|surat|salin|c|di|kantor|desa)', ['tidak pernah membuat surat salinan C.']] ,
['(apakah|saya|perlu|buat|e-ktp|jika|ingin|ktp|baru)', ['Saat ini semua KTP sudah wajib e-KTP']] ,
['(bagaimana|cara|buat|e-ktp|di|kantor|desa)', ['untuk membuat KTP hanya diperlukan Fotocopi Kartu Keluarga dan langsung ke Kantor Catatan Sipil Setempat.']] ,
['(bagaimana|cara|baik|data|ktp|yang|salah)', ['membawa KTP asli dan elemen pendukung data yang sebenarnya (KK)']] ,
['(apakah|saya|perlu|bawa|dokumen|lain|seperti|ijazah|akta|lahir|dan|kartu|keluarga|bagai|data|banding)', ['Ya.']] ,
['(bagaimana|cara|buat|ktp|baru|di|kantor|desa)', ['Pembuatan KTP tidak di Kantor Desa melainkan di Kantor Catatan Sipil']] ,
['(apakah|saya|perlu|bawa|surat|antar|dari|lurah|dan|foto|kopi|kartu|keluarga|ke|kantor|camat)', ['Ya. Tetapi Tidak Ada surat Pengantar. Hanya Fotocopi KK saja.']] ,
['(bagaimana|cara|salin|e-ktp|jika|saya|tidak|ingin|fotokopi)', ['Tidak ada informasi terkait hal tersebut']] ,
['(apakah|saya|perlu|masuk|e-ktp|ke|dalam|card|reader|untuk|dapat|salin)', ['Tidak ada informasi terkait hal tersebut']] ,
['(apa|itu|surat|pindah)', ['Surat Pindah merupakan dokumen yang telah di keluarkan dari Desa ataupun Dukcapil (apabila pindah sudah beda kabupaten) yang menerangkan bahwa telah pindah dari Desa Asal ke Desa Tujuan.']] ,
['(siapa|yang|bisa|aju|surat|pindah)', ['orang yang pindah']] ,
['(apa|saja|syarat|untuk|aju|surat|pindah)', ['Kartu Keluarga Asli dan Alamat Tujuan pindah']] ,
['(bagaimana|cara|aju|surat|pindah)', ['dengan datang ke kantor Desa membawa syarat yang ditentukan']] ,
['(berapa|lama|proses|buat|surat|pindah)', ['Apabila hanya pindah antar Desa perkiraan waktu kurang lebih 10 menit.']] ,
['(berapa|biaya|buat|surat|pindah)', ['Tidak Berbayar']] ,
['(apakah|saya|bisa|aju|surat|pindah|cara|online)', ['tidak bisa']] ,
['(apa|yang|harus|saya|laku|telah|dapat|surat|pindah)', ['serahkan surat pindah tersebut ke kaantor Desa yang menjadi tujuan. Maka akan di buatkan formulir untuk pembuatan Kartu Keluarga.']] ,
['(di|mana|saya|bisa|dapat|informasi|lebih|lanjut|tentang|surat|pindah)', ['melalui Kepala Dusun atau Kantor Desa']] ,
['(apa|itu|surat|terang|datang)', ['tidak ada surat keterangan datang']] ,
['(apa|itu|surat|terang|lahir)', ['Surat Keterangan lahir biasanya dikeluarkan oleh Puskesmas/Tempat Bersalin/Rumah sakit tempat si bayi lahir.']] ,
['(apa|itu|kartu|keluarga|kk)', ['kartu identitas keluarga yang memuat data tentang susunan, hubungan dan jumlah anggota keluarga. ']] ,
['(siapa|yang|hak|dapat|kk)', ['KK wajib dimiliki oleh setiap keluarga.']] ,
['(bagaimana|cara|dapat|kk)', ['apabila keluarga tersebut baru menikah maka keluarga tersebut melakukan pemecahan KK dari kedua orang tuanya masing-masing.']] ,
['(apa|saja|syarat|untuk|buat|kk|baru)', ['KK Dasar asli, Buku Menikah.']] ,
['(apa|saja|syarat|untuk|ubah|kk)', ['KK Asli, data dasar perubahan, mengisi formulir perubahan.']] ,
['(bagaimana|cara|buat|kk|baru|atau|ubah)', ['jawaban di pertanyaan no 60 dan 61.']] ,
['(berapa|lama|proses|buat|kk)', ['pelayanan dari kantor Desa hanya sebatas sampai dengan pengisian formulir, untuk proses selanjutnya berada di Kantor Dinas Catatan Sipil.']] ,
['(berapa|biaya|buat|kk)', ['Tidak Berbayar']] ,
['(apakah|saya|bisa|buat|kk|cara|online)', ['bisa melalui Dinas Catatan Sipil.']] ,
['(apa|yang|harus|saya|laku|jika|kk|hilang|atau|rusak)', ['membuat laporan ke Polsek dengan dasar surat dari Desa.']] ,
['(apa|itu|surat|domisili|tempat|tinggal)', ['Surat Domisili tempat tinggal merupakan surat yang menerangkan tempat tinggal dari warga tersebut.']] ,
['(siapa|yang|bisa|dapat|surat|domisili|tempat|tinggal)', ['setiap warga yang ingin mendapatkan surat tersebut di dukung dengan dasar-dasar yang real.']] ,
['(bagaimana|cara|dapat|surat|domisili|tempat|tinggal)', ['melalui kantor Desa.']] ,
['(apa|saja|syarat|untuk|dapat|surat|domisili|tempat|tinggal)', ['Memabawa Kartu Keluarga atau Surat Mandah.']] ,
['(berapa|lama|proses|buat|surat|domisili|tempat|tinggal)', ['Kurang lebih 10 Menit.']] ,
['(berapa|biaya|buat|surat|domisili|tempat|tinggal)', ['Tidak Berbayar']] ,
['(apakah|saya|bisa|dapat|surat|domisili|tempat|tinggal|cara|online)', ['Tidak']] ,
['(apa|yang|harus|saya|laku|jika|surat|domisili|tempat|tinggal|hilang|atau|rusak)', ['Membuat Laporan Ke Kantor Desa.']] ,
['(apa|itu|surat|terang|riwayat|tanah|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(siapa|yang|bisa|dapat|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(apa|saja|syarat|untuk|dapat|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(|bagaimana|cara|dapat|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(berapa|lama|proses|buat|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(berapa|biaya|buat|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(apakah|saya|bisa|dapat|skrt|cara|online)', ['Tidak ada informasi terkait hal tersebut']] ,
['(apa|yang|harus|saya|laku|jika|skrt|hilang|atau|rusak)', ['Tidak ada informasi terkait hal tersebut']] ,
['(apa|itu|surat|antar|skck)', ['Surat Pengantar SKCK adalah surat pengantar permohonan dari Desa kepada Polsek untuk memberikan Surat Keterangan Catatan Kriminal Seseorang']] ,
['(siapa|yang|bisa|buat|surat|antar|skck)', ['Setiap Orang yang sudah memiliki KTP/Wajib KTP (Umur 17 Tahun)']] ,
['(apa|saja|isi|surat|antar|skck)', ['Isi Surat Pengantar SKCK yaitu, Menjelaskan Identitas Seseorang, Data Kedua Orang Tua, Bukan anggota G30SPKI dan anggota organisasi terlarang lainnya.']] ,
['(bagaimana|cara|buat|surat|antar|skck)', ['melalui kantor Desa.']] ,
['(apakah|ada|format|baku|untuk|surat|antar|skck)', ['Ada format baku untuk surat pengantar SKCK']] ,
['(di|mana|saya|bisa|dapat|contoh|surat|antar|skck)', ['Di Kantor Desa']] ,
['(apakah|saya|bisa|guna|surat|antar|skck|dari|instansi|lain)', ['Tidak ada informasi terkait hal tersebut']] ,
['(apa|yang|harus|saya|laku|jika|surat|antar|skck|hilang|atau|rusak)', ['Membuat yang baru ke kantor Desa']] ,
['(apa|itu|surat|terang|tidak|mampu|sktm)', ['Surat yang menerangkan bahwa orang tersebut tergolong ekonomi lemah/tidak Mampu']] ,
['(siapa|yang|hak|dapat|sktm)', ['Warga yang dinyatakan tidak mampu dalam perekonomian ']] ,
['(apa|saja|syarat|untuk|dapat|sktm)', ['Membawa FC. KK']] ,
['(bagaimana|cara|dapat|sktm)', ['melalui kantor Desa.']] ,
['(berapa|lama|proses|buat|sktm)', ['Kurang lebih 10 Menit.']] ,
['(berapa|biaya|buat|sktm)', ['Tidak Berbayar']] ,
['(apakah|saya|bisa|dapat|sktm|cara|online)', ['tidak']] ,
['(apa|yang|harus|saya|laku|jika|sktm|hilang|atau|rusak)', ['membuat kembali di kantor Desa']] ,
['(apa|itu|surat|terang|usaha|sku)', ['Surat Keterangan usaha adalah surat yang menerangkan tentang usaha seseorang']] ,
['(siapa|yang|bisa|dapat|sku)', ['warga yang ingin mendapatkan surat tersebut dan benar memiliki usaha']] ,
['(apa|saja|syarat|untuk|dapat|sku)', ['FC KK atau FC KTP serta membawa Photo Usaha']] ,
['(bagaimana|cara|dapat|sku)', ['melalui kantor Desa.']] ,
['(berapa|lama|proses|buat|sku)', ['Kurang lebih 10 Menit.']] ,
['(berapa|biaya|buat|sku)', ['Tidak Berbayar']] ,
['(apakah|saya|bisa|dapat|sku|cara|online)', ['Tidak']] ,
['(apa|yang|harus|saya|laku|jika|sku|hilang|atau|rusak)', ['Mengurus kembali ke kantor Desa']] ,
['(apa|itu|kia)', ['KIA merupakan Kartu identitas seorang anak yang berlaku sampai usia 16 tahun dalam arti lain ini merupakan "KTP" nya anak-anak']] ,
['(apa|manfaat|kia)', ['sebagai kartu identitas, sama halnya dengan Kartu Tanda Penduduk (KTP)']] ,
['(siapa|yang|bisa|dapat|kia)', ['namun KIA diperuntukkan bagi anak-anak yang berusia antara 0-5 tahun dan 5-17 tahun kurang satu hari']] ,
['(bagaimana|cara|buat|kia)', ['dengan membawa Fotocopi KK, Fotocopi Akta Kelahiran dan Pasphoto 4x6(bagi yang berumur diatas 6 Tahun)']] ,
['(berapa|biaya|buat|kia)', ['gratis']] ,
['(bagaimana|jika|anak|hilang|dan|milik|kia)', ['Tidak ada informasi terkait hal tersebut']] ,
['(di|mana|informasi|lebih|lanjut|tentang|kia|bisa|dapat)', ['Kepala Dusun, Disdukcapil, dan Internet']] ,
['(apakah|anak|usia|di|bawah|5|tahun|wajib|milik|kia)', ['tidak diwajibkan tetapi disarankan memiliki KIA']] ,
['(apakah|kia|bisa|guna|untuk|naik|pesawat)', ['kurang tahu']] ,
['(apakah|kia|bisa|guna|untuk|buka|rekening|bank)', ['Tidak. Karena syarat pembukaan Rekening Baru harus memiliki KTP-El']] ,
['(di|mana|lokasi|daerah|sebut)', ['Desa Melati II Kecamatan Perbaungan Kabupaten Serdang Bedagai Provinsi Sumatera Utara']] ,
['(berapa|luas|wilayah|daerah|sebut)', ['Luas dari Desa Melati 2 yaitu 1.180 Ha']] ,
['(berapa|jumlah|duduk|daerah|sebut)', ['Jumlas penduduk dari Desa Melati 2 yaitu 18.231 Jiwa']] ,
['(bagaimana|batas|wilayah|daerah|sebut)', ['Sebelah Utara dengan Kelurahan Melati I, Sebelah Selatan Dengan Perkebunan, Sebelah barat Dengan Desa Citaman Jernih dan Perkebunan, Sebelah Timur dengan Desa Jatimulyo']] ,
['(siapa|yang|jadi|kepala|daerah|sebut)', ['Pemimpin dari Desa Melati 2 yaitu  seorang Kepala Desa']] ,
['(bagaimana|sejarah|singkat|daerah|sebut)', ['Menurut sejarah Desa Melati II adalah perjuangan Bapak Siswuyuono, dimana tanah Desa yang sekarang dinamakan Desa Melati II antara tahun 1948-1960 terbentuklah nama Kampung Melati. Dimana waku itu Bapak Siswuyuono menaman Pohon Bunga Melati bersama masyarakat di sekitar perkampungan dan tumbuh hingga saat ini. Lambat laun Kampung Melati tersebut bertambah ramai dan sesuai dengan tuntutan dan perkembangan zaman, saat ini kampung Melati telah berubah menjadi Desa Melati, maka jelaslah asal nama Melati II adalah pemetaan wilayah antara Kelurahan Melati I dan Desa Melati II.']] ,
['(apa|saja|budaya|yang|ada|di|daerah|sebut)', ['Budaya dan suku dari Desa Melati 2 yaitu jawa, banjar, melayu, batak, nias']] ,
['(apa|saja|makan|khas|daerah|sebut)', ['Tidak ada makanan khas dari Desa Melati 2']] ,
['(apa|saja|tempat|wisata|yang|ada|di|daerah|sebut)', ['Tempat wisaya dari Desa Melati 2 yaitu  Kebun Jeruk Petik Sendiri dan Palungguhan To Joyo']] ,
['(apa|saja|adat|istiadat|yang|ada|di|daerah|sebut)', ['jawa, banjar, melayu, batak, nias']] ,
['(bagaimana|sistem|perintah|di|daerah|sebut)', ['Sistem Pemerintahan Desa Murni']] ,
['(apa|saja|sumber|dapat|daerah|sebut)', ['APBN, Daerah, Pendapatan Desa, dan Pendapatan Lain yang tidak terikat']] ,
['(bagaimana|ada|ekonomi|di|daerah|sebut)', ['ekonomi di Desa Melati II tergolong ekonomi yang cukup baik']] ,
['(apa|saja|potensi|ekonomi|di|daerah|sebut)', ['Pertanian, Peternakan, Wisata, jasa dan Perdagangan']] ,
['(apa|saja|industri|yang|ada|di|daerah|sebut)', ['Industri Makanan, Meubel, Pakaian']] ,
['(bagaimana|ada|didik|di|daerah|sebut)', ['tersedia lengkap mulai dari PAUD hingga SMA']] ,
['(berapa|banyak|sekolah|yang|ada|di|daerah|sebut)', ['secara total ada 42 tempat pendidikan']] ,
['(bagaimana|ada|fasilitas|sehat|di|daerah|sebut)', ['Puskesmas, Praktek Bidan, Poliklinik, Balai Pengobatan dan Apotek']] ,
['(berapa|banyak|rumah|sakit|yang|ada|di|daerah|sebut)', ['Tidak ada Rumah Sakit di Desa Melati 2']] ,
['(berapa|jumlah|duduk|laki|di|daerah|sebut)', ['Jumlah penduduk laki laki di Desa Melati 2 yaitu 8.618']] ,
['(berapa|jumlah|duduk|perempuan|di|daerah|sebut)', ['Jumlah penduduk perempuan di Desa Melati 2 yaitu 9.613']] ,
['(berapa|rata|usia|duduk|di|daerah|sebut)', ['Rata rata usia dari penduduk Desa Melati 2 yaitu 19-59 Tahun']] ,
['(apa|saja|agama|yang|anut|oleh|duduk|di|daerah|sebut)', ['Agama yang ada di Desa Melati 2 yaitu Islam, Kristen, Katholik, Hindu, dan Budha']] ,
['(apa|saja|suku|bangsa|yang|ada|di|daerah|sebut)', ['jawa, banjar, melayu, batak, nias']] ,
['(bagaimana|tingkat|padat|duduk|di|daerah|sebut)', ['dari 1.180 Ha Jumlah Wilayah 195 Ha merupakan Pemukiman Masyarakat']] ,
['(apa|saja|kurang|daerah|sebut)', ['Kekuarangan, Jauh dari Kawasan industri sehingga sedikit lapangan kerja']] ,
['(apa|saja|unggul|daerah|sebut)', ['Keunggulan, Memiliki Lahan Pertanian yang Luas, Jumlah Penduduk Yang Banyak, Jarak Ke Ibu Kota Kecamatan dan Ibu Kota Kabupaten tidak Jauh.']] ,
['(apa|saja|tantang|yang|hadap|daerah|sebut)', ['Tantangan bisa menjadi Lumbung Pangan dengan potensi wilayah pertanian yang cukup luas.']] ,
['(apa|saja|peluang|yang|hadap|daerah|sebut)', ['Peluang bisa menjadi Lumbung Pangan dengan potensi wilayah pertanian yang cukup luas.']] ,
['(bagaimana|rencana|bangun|daerah|sebut|di|masa|depan)', ['Direncanakan Desa Melati II menjadi Desa Wisata yang sejahtera dengan melibatkan warga masyarakat']] ,
['(apa|itu|surat|yang|sifat|administratif)', ['Surat yang bersifat administratif adalah jenis surat yang berisi informasi tentang kegiatan administrasi, seperti laporan, pemberitahuan, permintaan, dan pernyataan. Surat ini digunakan untuk memberikan pesan atau informasi secara tertulis dari satu pihak ke pihak lain dalam organisasi atau instansi pemerintahan.']] ,
['(apa|saja|jenis|surat|administratif|yang|bisa|urus|di|kantor|desa|melati|2)', ['Pelayanan Administrasi Kependudukan:\n1. Surat Keterangan Pembuatan KTP\n3. Surat Keterangan PINDAH\n4. Surat Keterangan DATANG\n5. Surat Keterangan Lahir\n6. Surat Keterangan Kematian\n7. Perubahan Data KK\n8. Surat Domisili Tempat Tinggal\n9. Surat Keterangan Riwayat Tanah\nPelayanan Ketentraman dan Ketertiban (TRANTIB): \n1. Surat Pengantar SKCK\n2. Surat Pengantar Ijin Rame-rame(Izin Keramaian)']]
]