pairs = [
    ['(mulai|start|hello)', ['Hello saya Udin ada yang bisa saya bantu?']],

    ['(bagaimana|surat|terang|pergi)', 
     ['Untuk membuat surat keterangan bepergian di kantor desa, sebenarnya tidak diperlukan surat pengantar dari kantor desa. Namun, jika Anda membutuhkan surat pengantar untuk keperluan lain seperti izin keramaian pesta, berikut adalah tata cara mengurus surat pengantar izin keramaian pesta di kantor desa: 1. Siapkan surat permohonan izin keramaian pesta yang berisi informasi tentang jenis acara, tanggal dan waktu pelaksanaan, lokasi acara, dan jumlah peserta. 2. Siapkan dokumen persyaratan seperti Kartu Tanda Penduduk (KTP), Kartu Keluarga (KK), surat pengantar dari RT/RW, dan surat pernyataan kesanggupan untuk menanggung segala risiko yang terjadi selama acara berlangsung. 3. Datang ke kantor kelurahan/kepala desa dengan membawa surat permohonan dan dokumen persyaratan lainnya. 4. Mengisi formulir pembuatan izin keramaian pesta yang disediakan oleh petugas di kantor kelurahan/kepala desa. 5. Menyerahkan berkas persyaratan dan formulir ke petugas dan menunggu izin keramaian pesta selesai dibuat.']],

    ['(bagaimana|surat|terang|pergi|tidak|berada|tempat)', 
     ['Untuk membuat surat keterangan tidak berada di tempat di kantor desa, Anda dapat mengikuti beberapa langkah berikut: 1. Siapkan dokumen persyaratan seperti Kartu Tanda Penduduk (KTP), Kartu Keluarga (KK), dan surat pengantar dari RT/RW. 2. Buat surat permohonan surat keterangan tidak berada di tempat yang berisi informasi tentang alasan tidak berada di tempat, lama waktu tidak berada di tempat, dan tanggal kembali ke tempat asal. 3. Datang ke kantor kelurahan/kepala desa dengan membawa surat permohonan dan dokumen persyaratan lainnya. 4. Mengisi formulir pembuatan surat keterangan tidak berada di tempat yang disediakan oleh petugas di kantor kelurahan/kepala desa. 5. Menyerahkan berkas persyaratan dan formulir ke petugas dan menunggu surat keterangan tidak berada di tempat selesai dibuat.']],

    ['(bagaimana|surat|terang|beda|identitas)', 
     ['Berikut adalah tata cara membuat Surat Keterangan Beda Identitas di kantor desa: 1. Siapkan dokumen persyaratan seperti Kartu Tanda Penduduk (KTP), Kartu Keluarga (KK), dan dokumen yang membuktikan perbedaan identitas seperti akta kelahiran, ijazah, atau surat nikah. 2. Buat surat permohonan Surat Keterangan Beda Identitas yang berisi informasi tentang perbedaan identitas yang dimiliki dan alasan mengajukan surat keterangan. 3. Datang ke kantor kelurahan/kepala desa dengan membawa surat permohonan dan dokumen persyaratan lainnya. 4. Mengisi formulir pembuatan Surat Keterangan Beda Identitas yang disediakan oleh petugas di kantor kelurahan/kepala desa. 5. Menyerahkan berkas persyaratan dan formulir ke petugas dan menunggu Surat Keterangan Beda Identitas selesai dibuat.']],

    ['(bagaimana|cara|buat|ktp)', 
     ['1. desa (pemohon mengisi F.21 [permohonan KTP]-> ditandatangani KADES/LURAH. 2. kecamatan (surat F.21 dari desa diberikakan kepihak kecamatan dan ditandangani oleh CAMAT->operator memasukkan data pemohon kedalam sistem). 3. dukcapil (berkas F.21 beserta data pendukungknya diterima dan dicetak untuk validasi pada database lalu diaktivasi [enconding] KTP-El dsb->']],

    ['(bagaimana|cara|buat|akta|lahir)', 
     ['Berikut adalah tata cara membuat akta kelahiran di kantor desa: 1. Siapkan dokumen persyaratan seperti Surat Keterangan Kelahiran dari dokter/bidan/rumah sakit/penolong kelahiran, fotokopi Kartu Keluarga (KK), dan fotokopi Kartu Tanda Penduduk (KTP) orang tua. 2. Datang ke kantor kelurahan/kepala desa dengan membawa dokumen persyaratan yang telah disiapkan. 3. Mengisi formulir pembuatan akta kelahiran yang disediakan oleh petugas di kantor kelurahan/kepala desa. 4. Menyerahkan berkas persyaratan dan formulir ke petugas dan menunggu proses pembuatan akta kelahiran selesai.']]

]