pairs = [
['(biaya|buat|sku)', ['Tidak Berbayar']] ,
['(biaya|buat|kia)', ['gratis']] ,
['(saya|perlu|buat|surat|terang|panjang|ktp|jika|ingin|panjang|masa|laku|saya)', ['kalau KTP sudah elektrik, maka otomatis akan aktif seumur hidup. Meskipun tertera tanggal berlaku KTP tersebut maka dabaikan saja (karena KTP cetakan pertama masih ada tanggal berlakunya)']] ,
['(butuh|surat|panjang|ktp)', ['kalau KTP sudah elektrik, maka otomatis akan aktif seumur hidup. Meskipun tertera tanggal berlaku KTP tersebut maka dabaikan saja (karena KTP cetakan pertama masih ada tanggal berlakunya)']] ,
['(cara|buat|surat|terang|panjang|ktp|di|kantor|desa)', ['tidak ada surat perpanjangan KTP']] ,
['(cara|buat|surat|panjang|ktp)', ['tidak ada surat perpanjangan KTP']] ,
['(perlu|buat|surat|terang|buat|ktp)', ['tidak ada surat keterangan, untuk membuat KTP hanya diperlukan Fotocopi Kartu Keluarga dan langsung ke Kantor Catatan Sipil Setempat.']] ,
['(saya|perlu|buat|surat|terang|untuk|ktp)', ['tidak ada surat keterangan, untuk membuat KTP hanya diperlukan Fotocopi Kartu Keluarga dan langsung ke Kantor Catatan Sipil Setempat.']] ,
['(cara|buat|surat|terang|buat|ktp|di|kantor|desa)', ['tidak ada surat keterangan pembuatan KTP']] ,
['(cara|buat|surat|terang|buat|ktp)', ['tidak ada surat keterangan pembuatan KTP']] ,
['(saya|perlu|buat|surat|terang|pindah|jika|ingin|ubah|alamat|ktp|saya)', ['Tentu Saja. Apabila KTP Anda beralamat di Luar Desa Melati II dan sudah menetap bertempat tinggal di Desa Melati II, maka diharuskan membuat surat Pindah dari Daerah Asal, agar administrasi Anda sesuai dengan tempat tinggal anda yang sekarang']] ,
['(perlu|buat|surat|terang|pindah)', ['Tentu Saja perlu membuat surat keterangan pindah jika ingin mengubah alamat pada KTP anda apabila KTP Anda beralamat di Luar Desa Melati II dan sudah menetap bertempat tinggal di Desa Melati II, maka diharuskan membuat surat Pindah dari Daerah Asal, agar administrasi Anda sesuai dengan tempat tinggal anda yang sekarang']] ,
['(cara|buat|surat|terang|pindah|di|kantor|desa)', ['dengan membawa Kartu Keluarga Asli ke Kantor Desa Setempat dan data alamat tujuan pindah.']] ,
['(cara|buat|surat|pindah)', ['dengan membawa Kartu Keluarga Asli ke Kantor Desa Setempat dan data alamat tujuan pindah.']] ,
['(cara|buat|surat|terang|pindah)', ['dengan membawa Kartu Keluarga Asli ke Kantor Desa Setempat dan data alamat tujuan pindah.']] ,
['(saya|perlu|buat|surat|terang|datang|jika|ingin|ubah|status|ktp|saya)', ['KTP sudah seumur hidup, maka tidak bisa diganti apabila tidak ada elemen yang harus digantikan.']] ,
['(cara|buat|surat|terang|datang|di|kantor|desa)', ['Membawa Kartu Keluarga yang berksangkutan dan Kartu Keluarga rumah yang dikunjungi. Surat Keterangan Datang sama dengan Surat Keterangan Berkunjung.']] ,
['(saya|perlu|buat|surat|terang|lahir|jika|ingin|ktp|untuk|anak|saya)', ['WNI yang diwajibkan memiliki KTP-El adalah yang sudah berumur 17 Tahun. Maka Apabila Anak Anda sudah berumur 17 Tahun maka sudah bisa melakukan perekaman KTP di Kantor Catatan Sipil Setempat.']] ,
['(perlu|surat|terang|lahir|untuk|ktp)', ['WNI yang diwajibkan memiliki KTP-El adalah yang sudah berumur 17 Tahun. Maka Apabila Anak Anda sudah berumur 17 Tahun maka sudah bisa melakukan perekaman KTP di Kantor Catatan Sipil Setempat.']] ,
['(cara|buat|surat|terang|lahir|di|kantor|desa)', ['Surat Keterangan Lahir tidak dikeluarkan dari Kantor Desa melainkan dari Kantor Catatan Sipil yakni Akta Kelahiran. Syarat pembuatan Akta Kelahiran, yaitu dengan membawa : Fotocopi Kartu Keluarga, Fotocopi Buku Nikah Orang Tua, Fotocopi KTP Orang Tua, Fotocopi KTP 2 orang saksi (yang masih dalam 1 kabupaten), Surat Keterangan Lahir dari Bidan/Rumah Sakit Asli ke Kantor Desa Setempat dan akan dilengkapi dengan Formulir pembuatan Akta Kelahiran.']] ,
['(cara|buat|surat|terang|lahir)', ['Surat Keterangan Lahir tidak dikeluarkan dari Kantor Desa melainkan dari Kantor Catatan Sipil yakni Akta Kelahiran. Syarat pembuatan Akta Kelahiran, yaitu dengan membawa : Fotocopi Kartu Keluarga, Fotocopi Buku Nikah Orang Tua, Fotocopi KTP Orang Tua, Fotocopi KTP 2 orang saksi (yang masih dalam 1 kabupaten), Surat Keterangan Lahir dari Bidan/Rumah Sakit Asli ke Kantor Desa Setempat dan akan dilengkapi dengan Formulir pembuatan Akta Kelahiran.']] ,
['(saya|perlu|buat|surat|terang|mati|jika|ingin|ubah|status|ktp|saya)', ['Jika orang yang memiliki KTP sudah meninggal, maka KTP tersebut akan ditarik kembali oleh Kator Catatan Sipil Setempat dan akan digantikan dengan menimbulkan Akta Kematian orang tersebut.']] ,
['(perlu|buat|skk|untuk|ubah|status|pada|ktp)', ['Jika orang yang memiliki KTP sudah meninggal, maka KTP tersebut akan ditarik kembali oleh Kator Catatan Sipil Setempat dan akan digantikan dengan menimbulkan Akta Kematian orang tersebut.']] ,
['(cara|buat|skk)', ['dengan membawa Kartu Keluarga Asli ke Kantor Desa Setempat serta memberitahukan waktu meninggalnya [seperti Umur, Hari, Tanggal meninggalnya]']] ,
['(cara|buat|surat|terang|mati|di|kantor|desa)', ['dengan membawa Kartu Keluarga Asli ke Kantor Desa Setempat serta memberitahukan waktu meninggalnya [seperti Umur, Hari, Tanggal meninggalnya]']] ,
['(saya|perlu|buat|ubah|data|kk|jika|ingin|ubah|ktp|saya)', ['Ya. Apabila jika data di KK dan KTP terdapat elemen yang salah, maka harus melakukan Perubahan dahulu.']] ,
['(perlu|ubah|data|kk|jika|ingin|pada|ktp)', ['Ya. Apabila jika data di KK dan KTP terdapat elemen yang salah, maka harus melakukan Perubahan dahulu.']] ,
['(cara|ubah|data|kk|di|kantor|desa)', ['Dengan membawa Kartu Keluarga Asli dan elemen Pendukung Perubahan tersebut (seperti Ijazah atau Akta Kelahiran) serta membawa Materai 10.000.']] ,
['(ubah|data|kk)', ['Dengan membawa Kartu Keluarga Asli dan elemen Pendukung Perubahan tersebut (seperti Ijazah atau Akta Kelahiran) serta membawa Materai 10.000.']] ,
['(saya|perlu|buat|surat|domisili|tempat|tinggal|jika|ingin|ubah|alamat|ktp|saya)', ['Tidak. Apabila KK sudah beralamat/berdomisili ditempat tersebut, maka hanya perlu membawa fotocopi KK dan KTP asli ke Kantor Catatan Sipil untuk perubahan KTP.']] ,
['(perlu|buat|surat|tempat|tinggal|jika|ingin|megubah|alamat|ktp)', ['Tidak. Apabila KK sudah beralamat/berdomisili ditempat tersebut, maka hanya perlu membawa fotocopi KK dan KTP asli ke Kantor Catatan Sipil untuk perubahan KTP.']] ,
['(cara|buat|surat|domisili|tempat|tinggal|di|kantor|desa)', ['Apabila orang tersebut beralamat di Luar Desa Melati II, maka harus membuat Surat Mandah dari Desa Asal kemudian di bawa ke Kantor Desa Melati II serta membawa fotocopi KK.']] ,
['(cara|buat|surat|tempat|tinggal)', ['Apabila orang tersebut beralamat di Luar Desa Melati II, maka harus membuat Surat Mandah dari Desa Asal kemudian di bawa ke Kantor Desa Melati II serta membawa fotocopi KK.']] ,
['(saya|perlu|buat|surat|terang|riwayat|tanah|jika|ingin|ubah|status|ktp|saya)', ['Tidak.']] ,
['(perlu|buat|sk|tanah|jika|ubah|status|ktp)', ['Tidak.']] ,
['(cara|buat|surat|terang|riwayat|tanah|di|kantor|desa)', ['tidak pernah membuat surat keterangan riwayat tanah.']] ,
['(cara|buat|sk|tanah)', ['tidak pernah membuat surat keterangan riwayat tanah.']] ,
['(saya|perlu|buat|surat|salin|c|jika|ingin|ubah|status|ktp|saya)', ['tidak']] ,
['(perlu|calinan|c|jika|ubah|status|ktp)', ['tidak']] ,
['(cara|buat|surat|salin|c|di|kantor|desa)', ['tidak pernah membuat surat salinan C di kantor desa']] ,
['(cara|buat|salin|c)', ['tidak pernah membuat surat salinan C.']] ,
['(saya|perlu|buat|e-ktp|jika|ingin|ktp|baru)', ['Saat ini semua KTP sudah wajib e-KTP']] ,
['(perlu|ektp|tidak|untuk|buat|ktp|baru)', ['Saat ini semua KTP sudah wajib e-KTP']] ,
['(cara|buat|e-ktp|di|kantor|desa)', ['untuk membuat KTP hanya diperlukan Fotocopi Kartu Keluarga dan langsung ke Kantor Catatan Sipil Setempat.']] ,
['(baik|data|ktp|yang|salah)', ['membawa KTP asli dan elemen pendukung data yang sebenarnya (KK)']] ,
['(baik|data|ktp)', ['']] ,
['(saya|perlu|bawa|dokumen|lain|seperti|ijazah|akta|lahir|dan|kartu|keluarga|data|banding)', ['Ya.']] ,
['(dokumen|lengkap|buat|ktp)', ['Anda perlu membawa dokumen lain seperti ijazah, Akta Kelahiran, dan Kartu Keluarga sebagai data pembanding.']] ,
['(cara|buat|ktp|baru|di|kantor|desa)', ['Pembuatan KTP tidak di Kantor Desa melainkan di Kantor Catatan Sipil']] ,
['(saya|perlu|bawa|surat|antar|dari|lurah|dan|foto|kopi|kartu|keluarga|ke|kantor|camat)', ['Ya. Tetapi Tidak Ada surat Pengantar. Hanya Fotocopi KK saja.']] ,
['(perlu|surat|antar|untuk|buat|ktp)', ['Ya. Tetapi Tidak Ada surat Pengantar. Hanya Fotocopi KK saja.']] ,
['(salin|ktp|jika|saya|tidak|ingin|fotokopi)', ['Tidak ada informasi terkait hal tersebut']] ,
['(simpan|ktp)', ['Tidak ada informasi terkait hal tersebut']] ,
['(saya|perlu|masuk|e-ktp|ke|dalam|card|reader|untuk|dapat|salin)', ['Tidak ada informasi terkait hal tersebut']] ,
['(perlu|card|reader|untuk|salin|ktp)', ['Tidak ada informasi terkait hal tersebut']] ,
['(maksud|dengan|surat|pindah)', ['Surat Pindah merupakan dokumen yang telah di keluarkan dari Desa ataupun Dukcapil (apabila pindah sudah beda kabupaten) yang menerangkan bahwa telah pindah dari Desa Asal ke Desa Tujuan.']] ,
['(surat|pindah|adalah)', ['Surat Pindah merupakan dokumen yang telah di keluarkan dari Desa ataupun Dukcapil (apabila pindah sudah beda kabupaten) yang menerangkan bahwa telah pindah dari Desa Asal ke Desa Tujuan.']] ,
['(siapa|bisa|aju|surat|pindah)', ['orang yang pindah']] ,
['(syarat|buat|surat|pindah)', ['Kartu Keluarga Asli dan Alamat Tujuan pindah']] ,
['(syarat|untuk|aju|surat|pindah)', ['Kartu Keluarga Asli dan Alamat Tujuan pindah']] ,
['(cara|aju|surat|pindah)', ['dengan datang ke kantor Desa membawa syarat yang ditentukan']] ,
['(yang|harus|laku|telah|terima|surat|pindah)', ['serahkan surat pindah tersebut ke kaantor Desa yang menjadi tujuan. Maka akan di buatkan formulir untuk pembuatan Kartu Keluarga.']] ,
['(lama|proses|buat|surat|pindah)', ['Apabila hanya pindah antar Desa perkiraan waktu kurang lebih 10 menit.']] ,
['(informasi|lebih|lanjut|kena|surat|pindah)', ['anda dapat bertanya melalui Kepala Dusun atau Kepala Desa']] ,
['(biaya|surat|pindah)', ['Tidak Berbayar']] ,
['(saya|bisa|aju|surat|pindah|online)', ['tidak bisa']] ,
['(yang|harus|saya|laku|telah|dapat|surat|pindah)', ['serahkan surat pindah tersebut ke kaantor Desa yang menjadi tujuan. Maka akan di buatkan formulir untuk pembuatan Kartu Keluarga.']] ,
['(di|mana|saya|bisa|dapat|informasi|lebih|lanjut|tentang|surat|pindah)', ['melalui Kepala Dusun atau Kantor Desa']] ,
['(itu|surat|terang|datang)', ['tidak ada surat keterangan datang']] ,
['(itu|surat|terang|lahir)', ['Surat Keterangan lahir biasanya dikeluarkan oleh Puskesmas/Tempat Bersalin/Rumah sakit tempat si bayi lahir.']] ,
['(itu|kartu|keluarga|kk)', ['kartu identitas keluarga yang memuat data tentang susunan, hubungan dan jumlah anggota keluarga. ']] ,
['(siapa|yang|hak|dapat|kk)', ['KK wajib dimiliki oleh setiap keluarga.']] ,
['(cara|dapat|kk)', ['apabila keluarga tersebut baru menikah maka keluarga tersebut melakukan pemecahan KK dari kedua orang tuanya masing-masing.']] ,
['(syarat|untuk|buat|kk|baru)', ['KK Dasar asli, Buku Menikah.']] ,
['(syarat|untuk|ubah|kk)', ['KK Asli, data dasar perubahan, mengisi formulir perubahan.']] ,
['(cara|buat|kk|baru|atau|ubah|kk)', ['jawaban di pertanyaan no 60 dan 61.']] ,
['(lama|proses|buat|kartu|keluarga)', ['pelayanan dari kantor Desa hanya sebatas sampai dengan pengisian formulir, untuk proses selanjutnya berada di Kantor Dinas Catatan Sipil.']] ,
['(biaya|buat|kk)', ['Tidak Berbayar']] ,
['(saya|bisa|buat|kk|online)', ['Tidak bisa, Harus melalui Dinas Catatan Sipil.']] ,
['(yang|harus|saya|laku|jika|kk|hilang|atau|rusak)', ['membuat laporan ke Polsek dengan dasar surat dari Desa.']] ,
['(itu|surat|domisili|tempat|tinggal)', ['Surat Domisili tempat tinggal merupakan surat yang menerangkan tempat tinggal dari warga tersebut.']] ,
['(siapa|yang|bisa|dapat|surat|domisili|tempat|tinggal)', ['setiap warga yang ingin mendapatkan surat tersebut di dukung dengan dasar-dasar yang real.']] ,
['(dapat|surat|domisili|tempat|tinggal)', ['melalui kantor Desa.']] ,
['(syarat|untuk|dapat|surat|domisili|tempat|tinggal)', ['Memabawa Kartu Keluarga atau Surat Mandah.']] ,
['(lama|proses|buat|surat|domisili|tempat|tinggal)', ['Kurang lebih 10 Menit.']] ,
['(biaya|buat|surat|domisili|tempat|tinggal)', ['Tidak Berbayar']] ,
['(saya|bisa|dapat|surat|domisili|tempat|tinggal|online)', ['Tidak']] ,
['(yang|harus|saya|laku|jika|surat|domisili|tempat|tinggal|hilang|atau|rusak)', ['Membuat Laporan Ke Kantor Desa.']] ,
['(itu|surat|terang|riwayat|tanah|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(siapa|yang|bisa|dapat|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(syarat|untuk|dapat|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(dapat|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(lama|proses|buat|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(saya|bisa|dapat|skrt|online)', ['Tidak ada informasi terkait hal tersebut']] ,
['(yang|harus|saya|laku|jika|skrt|hilang|atau|rusak)', ['Tidak ada informasi terkait hal tersebut']] ,
['(surat|antar|skck)', ['Surat Pengantar SKCK adalah surat pengantar permohonan dari Desa kepada Polsek untuk memberikan Surat Keterangan Catatan Kriminal Seseorang']] ,
['(siapa|bisa|buat|surat|antar|skck)', ['Setiap Orang yang sudah memiliki KTP/Wajib KTP [Umur 17 Tahun]']] ,
['(perlu|surat|antar|buat|skck)', ['Ya, perlu.']],
['(isi|surat|antar|skck)', ['Isi Surat Pengantar SKCK yaitu, Menjelaskan Identitas Seseorang, Data Kedua Orang Tua, Bukan anggota G30SPKI dan anggota organisasi terlarang lainnya.']] ,
['(cara|buat|surat|antar|skck)', ['melalui kantor Desa.']] ,
['(format|baku|untuk|surat|antar|skck)', ['Ada format baku untuk surat pengantar SKCK (untuk lebih jelasnya bisa disesuaikan dengan melihat pada internet)']] ,
['(mana|saya|bisa|dapat|contoh|surat|antar|skck)', ['Di Kantor Desa']] ,
['(saya|bisa|guna|surat|antar|skck|dari|instansi|lain)', ['Tidak ada informasi terkait hal tersebut']] ,
['(harus|laku|surat|antar|skck|hilang|rusak)', ['Membuat yang baru ke kantor Desa']] ,
['(itu|surat|terang|tidak|mampu|sktm)', ['Surat yang menerangkan bahwa orang tersebut tergolong ekonomi lemah/tidak Mampu']] ,
['(siapa|bisa|dapat|sktm)', ['Warga yang dinyatakan tidak mampu dalam perekonomian ']] ,
['(syarat|dapat|sktm)', ['Membawa FC. KK']] ,
['(dapat|sktm)', ['melalui kantor Desa.']] ,
['(lama|proses|buat|sktm)', ['Kurang lebih 10 Menit.']] ,
['(biaya|buat|sktm)', ['Tidak Berbayar']] ,
['(saya|bisa|dapat|sktm|online)', ['tidak']] ,
['(yang|harus|saya|laku|jika|sktm|hilang|atau|rusak)', ['membuat kembali di kantor Desa']] ,
['(itu|surat|terang|usaha)', ['Surat Keterangan usaha adalah surat yang menerangkan tentang usaha seseorang']] ,
['(siapa|yang|bisa|dapat|sku)', ['warga yang ingin mendapatkan surat tersebut dan benar memiliki usaha']] ,
['(syarat|dapat|surat|terang|usaha)', ['FC KK atau FC KTP serta membawa Photo Usaha']] ,
['(cara|dapat|sku)', ['melalui kantor Desa.']] ,
['(lama|proses|buat|sku)', ['Kurang lebih 10 Menit.']] ,
['(saya|bisa|dapat|sku|online)', ['Tidak']] ,
['(yang|harus|saya|laku|jika|sku|hilang|atau|rusak)', ['Mengurus kembali ke kantor Desa']] ,
['(maksud|kia)', ['KIA merupakan Kartu identitas seorang anak yang berlaku sampai usia 16 tahun dalam arti lain ini merupakan "KTP" nya anak-anak']] ,
['(manfaat|kia)', ['sebagai kartu identitas, sama halnya dengan Kartu Tanda Penduduk (KTP)']] ,
['(siapa|dapat|kia)', ['namun KIA diperuntukkan bagi anak-anak yang berusia antara 0-5 tahun dan 5-17 tahun kurang satu hari']] ,
['(cara|buat|kia)', ['dengan membawa Fotocopi KK, Fotocopi Akta Kelahiran dan Pasphoto 4x6 [bagi yang berumur diatas 6 Tahun]']] ,
['(jika|anak|hilang|dan|milik|kia)', ['Tidak ada informasi terkait hal tersebut']] ,
['(di|mana|informasi|lebih|lanjut|tentang|kia|bisa|dapat)', ['Kepala Dusun, Disdukcapil, dan Internet']] ,
['(anak|usia|di|bawah|5|tahun|wajib|milik|kia)', ['tidak diwajibkan tetapi disarankan memiliki KIA']] ,
['(kia|bisa|guna|untuk|naik|pesawat)', ['kurang tahu']] ,
['(kia|bisa|guna|untuk|buka|rekening|bank)', ['Tidak. Karena syarat pembukaan Rekening Baru harus memiliki KTP-El']] ,
['(di|mana|lokasi|daerah|sebut)', ['Desa Melati II Kecamatan Perbaungan Kabupaten Serdang Bedagai Provinsi Sumatera Utara']] ,
['(luas|wilayah|daerah|sebut)', ['Luas dari Desa Melati II yaitu 1.180 Ha']] ,
['(berjumlah|duduk|daerah|sebut)', ['Jumlas penduduk dari Desa Melati II yaitu 18.231 Jiwa']] ,
['(batas|wilayah|daerah|sebut)', ['Sebelah Utara dengan Kelurahan Melati I, Sebelah Selatan Dengan Perkebunan, Sebelah barat Dengan Desa Citaman Jernih dan Perkebunan, Sebelah Timur dengan Desa Jatimulyo']] ,
['(siapa|yang|jadi|kepala|daerah|sebut)', ['Pemimpin dari Desa Melati II yaitu  seorang Kepala Desa']] ,
['(sejarah|singkat|daerah|sebut)', ['Menurut sejarah Desa Melati II adalah perjuangan Bapak Siswuyuono, dimana tanah Desa yang sekarang dinamakan Desa Melati II antara tahun 1948-1960 terbentuklah nama Kampung Melati. Dimana waku itu Bapak Siswuyuono menaman Pohon Bunga Melati bersama masyarakat di sekitar perkampungan dan tumbuh hingga saat ini. Lambat laun Kampung Melati tersebut bertambah ramai dan sesuai dengan tuntutan dan perkembangan zaman, saat ini kampung Melati telah berubah menjadi Desa Melati, maka jelaslah asal nama Melati II adalah pemetaan wilayah antara Kelurahan Melati I dan Desa Melati II.']] ,
['(budaya|yang|ada|di|desa|melati)', ['Budaya dan suku dari Desa Melati II yaitu jawa, banjar, melayu, batak, nias']] ,
['(makan|khas|daerah|sebut)', ['Tidak ada makanan khas dari Desa Melati II']] ,
['(tempat|wisata|yang|ada|di|daerah|sebut)', ['Tempat wisaya dari Desa Melati II yaitu  Kebun Jeruk Petik Sendiri dan Palungguhan To Joyo']] ,
['(adat|istiadat|yang|ada|di|daerah|sebut)', ['jawa, banjar, melayu, batak, nias']] ,
['(sistem|perintah|di|daerah|sebut)', ['Sistem Pemerintahan Desa Murni']] ,
['(sumber|dapat|daerah|sebut)', ['APBN, Daerah, Pendapatan Desa, dan Pendapatan Lain yang tidak terikat']] ,
['(ada|ekonomi|di|daerah|sebut)', ['ekonomi di Desa Melati II tergolong ekonomi yang cukup baik']] ,
['(potensi|ekonomi|di|daerah|sebut)', ['Pertanian, Peternakan, Wisata, jasa dan Perdagangan']] ,
['(industri|yang|ada|di|daerah|sebut)', ['Industri Makanan, Meubel, Pakaian']] ,
['(ada|didik|di|daerah|sebut)', ['tersedia lengkap mulai dari PAUD hingga SMA']] ,
['(banyak|sekolah|yang|ada|di|daerah|sebut)', ['se total ada 42 tempat pendidikan']] ,
['(ada|fasilitas|sehat|di|daerah|sebut)', ['Puskesmas, Praktek Bidan, Poliklinik, Balai Pengobatan dan Apotek']] ,
['(banyak|rumah|sakit|yang|ada|di|daerah|sebut)', ['Tidak ada Rumah Sakit di Desa Melati II']] ,
['(jumlah|duduk|laki|di|daerah|sebut)', ['Jumlah penduduk laki laki di Desa Melati II yaitu 8.618']] ,
['(jumlah|duduk|perempuan|di|daerah|sebut)', ['Jumlah penduduk perempuan di Desa Melati II yaitu 9.613']] ,
['(rata|usia|duduk|di|daerah|sebut)', ['Rata rata usia dari penduduk Desa Melati II yaitu 19-59 Tahun']] ,
['(agama|yang|anut|oleh|duduk|di|daerah|sebut)', ['Agama yang ada di Desa Melati II yaitu Islam, Kristen, Katholik, Hindu, dan Budha']] ,
['(suku|bangsa|yang|ada|di|daerah|sebut)', ['jawa, banjar, melayu, batak, nias']] ,
['(tingkat|padat|duduk|di|daerah|sebut)', ['dari 1.180 Ha Jumlah Wilayah 195 Ha merupakan Pemukiman Masyarakat']] ,
['(kurang|daerah|sebut)', ['Kekuarangan, Jauh dari Kawasan industri sehingga sedikit lapangan kerja']] ,
['(unggul|daerah|sebut)', ['Keunggulan, Memiliki Lahan Pertanian yang Luas, Jumlah Penduduk Yang Banyak, Jarak Ke Ibu Kota Kecamatan dan Ibu Kota Kabupaten tidak Jauh.']] ,
['(tantang|yang|hadap|daerah|sebut)', ['Tantangan bisa menjadi Lumbung Pangan dengan potensi wilayah pertanian yang cukup luas.']] ,
['(peluang|yang|hadap|daerah|sebut)', ['Peluang bisa menjadi Lumbung Pangan dengan potensi wilayah pertanian yang cukup luas.']] ,
['(rencana|bangun|daerah|sebut|di|masa|depan)', ['Direncanakan Desa Melati II menjadi Desa Wisata yang sejahtera dengan melibatkan warga masyarakat']] ,
['(itu|surat|yang|sifat|administratif)', ['Surat yang bersifat administratif adalah jenis surat yang berisi informasi tentang kegiatan administrasi, seperti laporan, pemberitahuan, permintaan, dan pernyataan. Surat ini digunakan untuk memberikan pesan atau informasi se tertulis dari satu pihak ke pihak lain dalam organisasi atau instansi pemerintahan.']] ,
['(jenis|surat|administratif|yang|bisa|urus|di|kantor|desa|melati|2)', ['Pelayanan Administrasi Kependudukan:<br />1. Surat Keterangan Pembuatan KTP<br />3. Surat Keterangan PINDAH<br />4. Surat Keterangan DATANG<br />5. Surat Keterangan Lahir<br />6. Surat Keterangan Kematian<br />7. Perubahan Data KK<br />8. Surat Keterangan Riwayat Tanah<br />Pelayanan Ketentraman dan Ketertiban (TRANTIB): <br />1. Surat Pengantar SKCK<br />2. Surat Pengantar Ijin Rame-rame(Izin Keramaian)']] ,
['(siapa|yang|boleh|dapat|kartu|keluarga)', ['KK wajib dimiliki oleh setiap keluarga.']] ,
['(cara|buat|kartu|keluarga)', ['apabila keluarga tersebut baru menikah maka keluarga tersebut melakukan pemecahan KK dari kedua orang tuanya masing-masing.']] ,
['(syarat|untuk|buat|kartu|keluarga|baru)', ['KK Dasar asli, Buku Menikah.']] ,
['(syarat|untuk|ganti|kartu|kerluarga)', ['KK Asli, data dasar perubahan, mengisi formulir perubahan.']] ,
['(syarat|untuk|rubah|kartu|kerluarga)', ['KK Asli, data dasar perubahan, mengisi formulir perubahan.']] ,
['(lama|buat|kartu|keluarga)', ['pelayanan dari kantor Desa hanya sebatas sampai dengan pengisian formulir, untuk proses selanjutnya berada di Kantor Dinas Catatan Sipil.']] ,
['(waktu|untuk|buat|kartu|keluarga)', ['pelayanan dari kantor Desa hanya sebatas sampai dengan pengisian formulir, untuk proses selanjutnya berada di Kantor Dinas Catatan Sipil.']] ,
['(biaya|buat|kartu|keluarga)', ['Tidak Berbayar']] ,
['(bisa|bikin|kartu|keluarga|online)', ['bisa melalui Dinas Catatan Sipil.']] ,
['(saya|bisa|buat|kartu|kelurga|online)', ['bisa melalui Dinas Catatan Sipil.']] ,
['(yang|harus|laku|jika|kartu|keluarga|hilang|atau|rusak)', ['membuat laporan ke Polsek dengan dasar surat dari Desa.']] ,
['(yang|harus|saya|laku|jika|kartu|keluarga|hilang|atau|rusak)', ['membuat laporan ke Polsek dengan dasar surat dari Desa.']] ,
['(itu|surat|terang|riwayat|tanah|skrt)', ['Tidak ada informasi terkait hal tersebut']] ,
['(siapa|yang|boleh|punya|surat|terang|riwayat|tanah)', ['Tidak ada informasi terkait hal tersebut']] ,
['(siapa|yang|bisa|dapat|surat|terang|riwayat|tanah)', ['Tidak ada informasi terkait hal tersebut']] ,
['(syarat|dapat|surat|terang|riwayat|tanah)', ['Tidak ada informasi terkait hal tersebut']] ,
['(dapat|surat|terang|riwayat|tanah)', ['Tidak ada informasi terkait hal tersebut']] ,
['(lama|proses|buat|surat|terang|riwayat|tanah)', ['Tidak ada informasi terkait hal tersebut']] ,
['(biaya|buat|surat|terang|riwayat|tanah)', ['Tidak ada informasi terkait hal tersebut']] ,
['(bisa|dapat|surat|terang|riwayat|tanah|online)', ['Tidak ada informasi terkait hal tersebut']] ,
['(jika|surat|terang|riwayat|tanah|hilang)', ['Tidak ada informasi terkait hal tersebut']] ,
['(jika|surat|terang|riwayat|tanah|rusak)', ['Tidak ada informasi terkait hal tersebut']] ,
['(surat|antar|terang|catat|polisi)', ['Surat Pengantar SKCK adalah surat pengantar permohonan dari Desa kepada Polsek untuk memberikan Surat Keterangan Catatan Kriminal Seseorang']] ,
['(siapa|buat|surat|antar|skck)', ['Setiap Orang yang sudah memiliki KTP/Wajib KTP (Umur 17 Tahun)']] ,
['(isi|surat|antar|terang|catat|polisi)', ['Isi Surat Pengantar SKCK yaitu, Menjelaskan Identitas Seseorang, Data Kedua Orang Tua, Bukan anggota G30SPKI dan anggota organisasi terlarang lainnya.']] ,
['(cara|buat|surat|antar|terang|catat|polisi)', ['melalui kantor Desa.']] ,
['(format|untuk|surat|antar|terang|catat|polisi)', ['Ada format baku untuk surat pengantar SKCK (untuk lebih jelasnya bisa disesuaikan dengan melihat pada internet)']] ,
['(di|mana|dapat|contoh|surat|antar|terang|catat|polisi)', ['Di Kantor Desa']] ,
['(bisa|pakai|surat|antar|terang|catat|polisi|dari|lembaga|lain)', ['Tidak ada informasi terkait hal tersebut']] ,
['(yang|harus|saya|laku|jika|surat|antar|terang|catat|polisi|hilang)', ['Membuat yang baru ke kantor Desa']] ,
['(yang|harus|saya|laku|jika|surat|antar|terang|catat|polisi|rusak)', ['Membuat yang baru ke kantor Desa']] ,
['(itu|surat|terang|tidak|mampu|sktm)', ['Surat yang menerangkan bahwa orang tersebut tergolong ekonomi lemah/tidak Mampu']] ,
['(yang|boleh|milik|surat|terang|tidak|mampu)', ['Warga yang dinyatakan tidak mampu dalam perekonomian ']] ,
['(yang|boleh|punya|surat|terang|tidak|mampu)', ['Warga yang dinyatakan tidak mampu dalam perekonomian ']] ,
['(yang|boleh|dapat|surat|terang|tidak|mampu)', ['Warga yang dinyatakan tidak mampu dalam perekonomian ']] ,
['(syarat|untuk|dapat|surat|terang|tidak|mampu)', ['Membawa FC. KK']] ,
['(memempunyai|surat|terang|tidak|mampu)', ['melalui kantor Desa.']] ,
['(proses|buat|surat|terang|tidak|mampu)', ['Kurang lebih 10 Menit.']] ,
['(biaya|buat|surat|terang|tidak|mampu)', ['Tidak Berbayar']] ,
['(bisa|dapat|surat|terang|tidak|mampu|online)', ['tidak']] ,
['(jika|surat|terang|tidak|mampu|hilang)', ['membuat kembali di kantor Desa']] ,
['(jika|surat|terang|tidak|mampu|rusak)', ['membuat kembali di kantor Desa']] ,
['(erti|surat|terang|usaha)', ['Surat Keterangan usaha adalah surat yang menerangkan tentang usaha seseorang']] ,
['(siapa|yang|bisa|dapat|surat|terang|usaha)', ['warga yang ingin mendapatkan surat tersebut dan benar memiliki usaha']] ,
['(syarat|untuk|dapat|surat|terang|usaha)', ['FC KK atau FC KTP serta membawa Photo Usaha']] ,
['(buat|surat|terang|usaha)', ['melalui kantor Desa.']] ,
['(waktu|buat|surat|terang|usaha)', ['Kurang lebih 10 Menit.']] ,
['(biaya|buat|surat|terang|usaha)', ['Tidak Berbayar']] ,
['(bisa|dapat|surat|terang|usaha|online)', ['Tidak']] ,
['(yang|laku|jika|surat|terang|usaha|hilang)', ['Mengurus kembali ke kantor Desa']] ,
['(yang|laku|jika|surat|terang|usaha|rusak)', ['Mengurus kembali ke kantor Desa']] ,
['(itu|kia)', ['KIA merupakan Kartu identitas seorang anak yang berlaku sampai usia 16 tahun dalam arti lain ini merupakan "KTP" nya anak-anak']] ,
['(manfaat|kartu|identitas|anak)', ['sebagai kartu identitas, sama halnya dengan Kartu Tanda Penduduk (KTP)']] ,
['(siapa|yang|dapat|kartu|identitas|anak)', ['namun KIA diperuntukkan bagi anak-anak yang berusia antara 0-5 tahun dan 5-17 tahun kurang satu hari']] ,
['(cara|buat|kartu|identitas|anak)', ['dengan membawa Fotocopi KK, Fotocopi Akta Kelahiran dan Pasphoto 4x6(bagi yang berumur diatas 6 Tahun)']] ,
['(biaya|buat|kartu|identitas|anak)', ['gratis']] ,
['(jika|anak|hilang|dan|milik|kartu|identitas|anak)', ['Tidak ada informasi terkait hal tersebut']] ,
['(di|mana|informasi|lebih|lanjut|tentang|kartu|identitas|anak|bisa|dapat)', ['Kepala Dusun, Disdukcapil, dan Internet']] ,
['(anak|usia|di|bawah|5|tahun|wajib|milik|kartu|identitas|anak)', ['tidak diwajibkan tetapi disarankan memiliki KIA']] ,
['(perlu|buat|surat|terang|pindah|untuk|ubah|alamat|ktp)', ['Tentu Saja perlu membuat surat keterangan pindah jika ingin mengubah alamat pada KTP anda apabila KTP Anda beralamat di Luar Desa Melati II dan sudah menetap bertempat tinggal di Desa Melati II, maka diharuskan membuat surat Pindah dari Daerah Asal, agar administrasi Anda sesuai dengan tempat tinggal anda yang sekarang']] ,
['(bikin|surat|terang|datang)', ['Membawa Kartu Keluarga yang berksangkutan dan Kartu Keluarga rumah yang dikunjungi. Surat Keterangan Datang sama dengan Surat Keterangan Berkunjung.']] ,
['(perlu|buat|surat|terang|lahir|jika|ingin|ktp|untuk|anak)', ['WNI yang diwajibkan memiliki KTP-El adalah yang sudah berumur 17 Tahun. Maka Apabila Anak Anda sudah berumur 17 Tahun maka sudah bisa melakukan perekaman KTP di Kantor Catatan Sipil Setempat.']] ,
['(perlu|buat|surat|terang|mati|jika|ingin|ubah|status|ktp)', ['Jika orang yang memiliki KTP sudah meninggal, maka KTP tersebut akan ditarik kembali oleh Kator Catatan Sipil Setempat dan akan digantikan dengan menimbulkan Akta Kematian orang tersebut.']] ,
['(perlu|buat|skk|untuk|ubah|status|pada|ktp)', ['Jika orang yang memiliki KTP sudah meninggal, maka KTP tersebut akan ditarik kembali oleh Kator Catatan Sipil Setempat dan akan digantikan dengan menimbulkan Akta Kematian orang tersebut.']] ,
['(cara|buat|surat|terang|mati)', ['dengan membawa Kartu Keluarga Asli ke Kantor Desa Setempat serta memberitahukan waktu meninggalnya (seperti Umur, Hari, Tanggal meninggalnya)']] ,
['(perlu|buat|ubah|data|kartu|keluarga|jika|ubah|ktp)', ['Ya. Apabila jika data di KK dan KTP terdapat elemen yang salah, maka harus melakukan Perubahan dahulu.']] ,
['(perlu|ubah|data|kartu|keluarga|jika|pada|ktp)', ['Ya. Apabila jika data di KK dan KTP terdapat elemen yang salah, maka harus melakukan Perubahan dahulu.']] ,
['(cara|buat|ubah|data|kartu|keluarga)', ['Dengan membawa Kartu Keluarga Asli dan elemen Pendukung Perubahan tersebut (seperti Ijazah atau Akta Kelahiran) serta membawa Materai 10.000.']] ,
['(ubah|data|kartu|keluarga)', ['Dengan membawa Kartu Keluarga Asli dan elemen Pendukung Perubahan tersebut (seperti Ijazah atau Akta Kelahiran) serta membawa Materai 10.000.']] ,
['(perlu|buat|surat|domisili|tempat|tinggal|ubah|alamat|ktp)', ['Tidak. Apabila KK sudah beralamat/berdomisili ditempat tersebut, maka hanya perlu membawa fotocopi KK dan KTP asli ke Kantor Catatan Sipil untuk perubahan KTP.']] ,
['(perlu|buat|surat|tempat|tinggal|megubah|alamat|ktp)', ['Tidak. Apabila KK sudah beralamat/berdomisili ditempat tersebut, maka hanya perlu membawa fotocopi KK dan KTP asli ke Kantor Catatan Sipil untuk perubahan KTP.']] ,
['(buat|surat|domisili|tempat|tinggal)', ['Apabila orang tersebut beralamat di Luar Desa Melati II, maka harus membuat Surat Mandah dari Desa Asal kemudian di bawa ke Kantor Desa Melati II serta membawa fotocopi KK.']] ,
['(buat|surat|tempat|tinggal)', ['Apabila orang tersebut beralamat di Luar Desa Melati II, maka harus membuat Surat Mandah dari Desa Asal kemudian di bawa ke Kantor Desa Melati II serta membawa fotocopi KK.']] ,
['(perlu|buat|surat|terang|riwayat|tanah|jika|ubah|status|ktp)', ['Tidak.']] ,
['(perlu|buat|surat|terang|tanah|jika|ubah|status|ktp)', ['Tidak.']] ,
['(cara|buat|surat|terang|riwayat|tanah)', ['tidak pernah membuat surat keterangan riwayat tanah.']] ,
['(cara|buat|sk|tanah)', ['tidak pernah membuat surat keterangan riwayat tanah.']] ,
['(saya|perlu|buat|surat|salin|c|jika|ingin|ubah|status|ktp|saya)', ['tidak']] ,
['(perlu|calinan|c|jika|ubah|status|ktp)', ['tidak']] ,
['(cara|buat|surat|salin|c|di|kantor|desa)', ['tidak pernah membuat surat salinan C di kantor desa']] ,
['(cara|buat|salin|c)', ['tidak pernah membuat surat salinan C.']] ,
['(perlu|buat|e-ktp|jik|ingin|ktp|baru)', ['Saat ini semua KTP sudah wajib e-KTP']] ,
['(perlu|ektp|tidak|untuk|buat|ktp|baru)', ['Saat ini semua KTP sudah wajib e-KTP']] ,
['(cara|buat|e-ktp)', ['untuk membuat KTP hanya diperlukan Fotocopi Kartu Keluarga dan langsung ke Kantor Catatan Sipil Setempat.']] ,
['(cara|buat|ktp)', ['untuk membuat KTP hanya diperlukan Fotocopi Kartu Keluarga dan langsung ke Kantor Catatan Sipil Setempat.']] ,
['(baik|data|ktp|yang|salah)', ['membawa KTP asli dan elemen pendukung data yang sebenarnya (KK)']] ,
['(baik|data|ktp)', ['']] ,
['(perlu|bawa|dokumen|lain|bagai|data|banding)', ['Ya. Anda perlu membawa dokumen lain seperti ijazah, Akta Kelahiran, dan Kartu Keluarga sebagai data pembanding.']] ,
['(perlu|bawa|dokumen|lain|untuk|buat|ktp)', ['Ya. Anda perlu membawa dokumen lain seperti ijazah, Akta Kelahiran, dan Kartu Keluarga sebagai data pembanding.']] ,
['(perlu|bawa|dokumen|lain)', ['Ya. Anda perlu membawa dokumen lain seperti ijazah, Akta Kelahiran, dan Kartu Keluarga sebagai data pembanding.']] ,
['(dokumen|lengkap|buat|ktp)', ['Anda perlu membawa dokumen lain seperti ijazah, Akta Kelahiran, dan Kartu Keluarga sebagai data pembanding.']] ,
['(dokumen|lengkap|untuk|buat|ktp)', ['Anda perlu membawa dokumen lain seperti ijazah, Akta Kelahiran, dan Kartu Keluarga sebagai data pembanding.']] ,
['(cara|buat|ktp|baru)', ['Pembuatan KTP tidak di Kantor Desa melainkan di Kantor Catatan Sipil']] ,
['(perlu|surat|antar|lurah|fotokopi|kartu|keluarga|kantor|camat)', ['Ya. Tetapi Tidak Ada surat Pengantar. Hanya Fotocopi KK saja.']] ,
['(perlu|surat|antar|untuk|buat|ktp)', ['Ya. Tetapi Tidak Ada surat Pengantar. Hanya Fotocopi KK saja.']] ,
['(salin|e-ktp|jika|tidak|ingin|fotokopi)', ['Tidak ada informasi terkait hal tersebut']] ,
['(simpan|e-ktp)', ['Tidak ada informasi terkait hal tersebut']] ,
['(perlu|masuk|e-ktp|ke|mesin|untuk|dapat|salin)', ['Tidak ada informasi terkait hal tersebut']] ,
['(perlu|card|reader|untuk|salin|ktp)', ['Tidak ada informasi terkait hal tersebut']] ,
['(perlu|mesin|untuk|salin|ktp)', ['Tidak ada informasi terkait hal tersebut']] ,
['(itu|surat|pindah)', ['Surat Pindah merupakan dokumen yang telah di keluarkan dari Desa ataupun Dukcapil (apabila pindah sudah beda kabupaten) yang menerangkan bahwa telah pindah dari Desa Asal ke Desa Tujuan.']] ,
['(surat|pindah|adalah)', ['Surat Pindah merupakan dokumen yang telah di keluarkan dari Desa ataupun Dukcapil (apabila pindah sudah beda kabupaten) yang menerangkan bahwa telah pindah dari Desa Asal ke Desa Tujuan.']] ,
['(yang|bisa|buat|surat|pindah)', ['orang yang pindah']] ,
['(syarat|buat|surat|pindah)', ['Kartu Keluarga Asli dan Alamat Tujuan pindah']] ,
['(syarat|untuk|buat|surat|pindah)', ['Kartu Keluarga Asli dan Alamat Tujuan pindah']] ,
['(aju|surat|pindah)', ['dengan datang ke kantor Desa membawa syarat yang ditentukan']] ,
['(cara|buat|surat|pindah)', ['dengan datang ke kantor Desa membawa syarat yang ditentukan']] ,
['(telah|terima|surat|pindah|terus|apalagi)', ['serahkan surat pindah tersebut ke kaantor Desa yang menjadi tujuan. Maka akan di buatkan formulir untuk pembuatan Kartu Keluarga.']] ,
['(lama|buat|surat|pindah)', ['Apabila hanya pindah antar Desa perkiraan waktu kurang lebih 10 menit.']] ,
['(informasi|lebih|tentang|surat|pindah)', ['anda dapat bertanya melalui Kepala Dusun atau Kepala Desa']] ,
['(bisa|aju|surat|pindah|online)', ['tidak bisa']] ,
['(yang|laku|telah|dapat|surat|pindah)', ['serahkan surat pindah tersebut ke kaantor Desa yang menjadi tujuan. Maka akan di buatkan formulir untuk pembuatan Kartu Keluarga.']] ,
['(yang|laku|telah|punya|surat|pindah)', ['serahkan surat pindah tersebut ke kaantor Desa yang menjadi tujuan. Maka akan di buatkan formulir untuk pembuatan Kartu Keluarga.']] ,
['(mana|bisa|dapat|informasi|lebih|kena|surat|pindah)', ['melalui Kepala Dusun atau Kantor Desa']] ,
['(mana|bisa|dapat|informasi|lebih|tentang|surat|pindah)', ['melalui Kepala Dusun atau Kantor Desa']] ,
['(surat|terang|datang|adalah)', ['tidak ada surat keterangan datang']] ,
['(surat|terang|lahir|adalah)', ['Surat Keterangan lahir biasanya dikeluarkan oleh Puskesmas/Tempat Bersalin/Rumah sakit tempat si bayi lahir.']] ,
['(mulai|chatbot|melati)', ["SELAMAT DATANG DI CHATBOT MELATI II"
                            " "
                            "Anda bisa bertanya terkait informasi yang ingin anda ketahui melalui layanan ini. Adapun pertanyaan yang diajukan berkaitan dengan :"
                            "(KTP)  (SURAT PINDAH) (SURAT KETERANGAN DOMISILI)  (SKCK)  (SKTM)  (SKU)  (KIA)  (PROFILE) "
                            "Anda bisa mengklik salah 1 menu diatas"]] ,
['(ktp)', ['Berikut pertanyaan mengenai KTP :'
           '(Bagaimana cara buat KTP?) (Apa saja dokumen pelengkap pembuatan KTP?) (Apakah perlu membuat surat keterangan pembuatan KTP?)']],
['(surat|pindah)', ['Berikut pertanyaan mengenai Surat Pindah :'
                    '(Apa yang dimaksud dengan surat pindah?) (Siapa yang bisa mengajukan surat pindah?) (Bagaimana cara mengajukan surat pindah?)']],
['(kartu|keluarga)', ['Berikut pertanyaan mengenai Kartu Keluarga :'
                      '(Bagaimana cara mendapatkan Kartu Keluarga?) (Berapa lama proses pembuatan Kartu Keluarga?)']],
['(surat|keterangan|domisili)', ['Berikut pertanyaan mengenai Surat Keterangan Domisili: '
                                 '(Apa yang dimaksud surat domisili tempat tinggal?) (Siapa saja yang bisa mendapatkan surat domisili tempat tinggal?) (Apa saja syarat untuk mendapatkan surat domisili tempat tinggal?)']],
['(skck)', ['Berikut pertanyaan mengenai SKCK: '
            '(Apakah perlu surat pengantar untuk membuat SKCK?) (Siapa saja yang bisa membuat surat pengantar SKCK?) (Apakah ada format baku untuk surat pengantar SKCK?)']],
['(sktm)', ['berikut pertanyaan mengenai SKTM: '
            '(Siapa saja yang bisa mendapatkan SKTM?) (Apa saja syarat untuk mendapatkan SKTM?) (Berapa biaya pembuatan SKTM?)']],
['(sku)', ['Berikut pertanyaan mengenai SKU: '
           '(Apa pengertian Surat Keterangan Usaha?) (Bagaimana cara mendapatkan SKU?) (Apa saja syarat untuk mendapatkan Surat Keterangan Usaha?)']],
['(kia)', ['Berikut pertanyaan mengenai KIA: '
           '(Apa yang dimaksud dengan itu KIA?) (Bagaimana cara membuat KIA?) (Siapa saja yang bisa mendapatkan KIA?)']],
['profile', ['Berikut pertanyaan mengenai PROFILE:'
             '(Bagaimana sejarah singkat daerah tersebut?) (Apa saja budaya yang ada di Desa Melati II?) (Apa saja makanan khas daerah tersebut?) (Apa saja tempat wisata yang ada di daerah tersebut?) (Apa saja adat istiadat yang ada di daerah tersebut?)']]
]